### ISSUE TITLE
Low Hanging Fruit for better development experience with Backstage

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#11061]
### Switch to PostgreSQL
- [x] Include `pg` dependency in `create-app` template
- [x] Add postgres config section to app-config.yaml 
### Github backend with PAT
- [x] Document how to generate a token and link to docs from app-config.yaml
- [x] Remove inline of token in https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration 
- [x] #11069
### Set up GitHub OAuth App for sign-in with guest resolver
- [x] Fix documentation so that configure auth naturally takes you to the identityResolver @Rugvip #11071
- [x] Add example sign-in resolver to create-app template, post https://github.com/backstage/backstage/pull/10300, maybe commented out? @Rugvip #11192

### Define 3 custom mock entities in GitHub + register them manually
- [x] Probably add sample catalog data to the create-app template 
- [x] #11062 
- [x] #11068 
###  Get the scaffolder plugin running with one custom template in GitHub
- [x] Add sample template to create-app
- [x] Remove GitHub action workflows from all sample templates in software templates
- [x] https://github.com/backstage/software-templates/pull/17
### Github app for integration
- [x] Recommend creation of demo org if needed @benjdlambert
- [x] https://github.com/backstage/backstage/pull/11206
### Github Discovery provider
- [x] Update docs/integrations/github/discovery.md to remove section about Etag(we got it already)
- [x] Update GitHub discovery integration docs to not only point to PAT, but also mention GitHub Apps
- [x] #11085 
### Github org ingestion
- [x] Update docs to describe how to set up the provider instead #11249
- [x] Power up the github-app CLI to help guide what permissions should be enabled @jhaals #11213
- [x] Support new scheduling API inversion for GitHubOrgEntityProvider #11249
- [x] Investigate whether we can use human readable duration strings to avoid the luxon dependency for task scheduling. @jhaals #11245
### Switch to Github Sign-in resolver
- [x] Add built-in username sign-in resolver for GitHub - combined with in-line create-app example @Rugvip #11192
- [x] Add technical docs on debugging auth, inspecting token, etc @Rugvip #11198
### Switch to Oauth2-proxy
- [x] Document ProxiedSignInPage setup + example with environment selection. Perhaps select env based on hostname? @Rugvip #11217
- [x] Switch OAuth2 Proxy docs to use alpha config instead + header injection @Rugvip #11216 (not really but either method works now)
- [x] Refactor oauth2-proxy provider to provide headers and stop parsing the token. Provide some examples of different usages @Rugvip #11216
### Multi backends
- [ ] ~backstage-cli create --select backend~ @Rugvip #11244
- [x] Tweak .dockerignore so that it doesn’t require new entries for added backend packages @Rugvip #11243

**Comment by Rugvip** [comment]
All items are dealt with! :shipit:
