### ISSUE TITLE
Tweaks to make it easier to get up and running with Backstage

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#11954]
This is a second round of tweaks that we've identified as part of evaluating the steps to get Backstage up and running in production over in https://github.com/Rugvip/backstage-prod-diff. Glad to say that we've so far been able to reduce the number of steps required to set up our imagined target Backstage project by 35%. Apart from these smaller tweaks we also hope that the structure proposed in #11611 will provide a another significant improvement to the initial setup experience.

## High Prio (v1.3)

- [x] Add example entities to production image, or remove them from production config. #11997
- [x] Update SignInPage example in getting started guide. #11927
- [x] Add guest resolver to auth setup in template. #11937
- [x] Add org members read permission to the GitHub app CLI. #11931
- [x] Add users/ownership information somewhere in the frontend. #11974
- [x] Fix the inconsistent oauth2proxy/oauth2Proxy casing. #11975

## Low Prio

- [x] Make it easier to find the built-in resolvers in the docs. #12020
- [ ] Add signal handler for node process to exit quickly in docker. #12017
- [ ] Figure out how to improve relative file locations so that they are more intuitive. Create a lightweight RFC to gather feedback. #11993
- [ ] Fix logout for proxy providers. #12016
- [x] Stronger encouragement in the OAuth2 Proxy auth docs to point people to the proxy sign-in page docs. #12020

**Comment by Rugvip** [comment]
Closing as the remaining low prio items are captured in separate issues
