### ISSUE TITLE
Catalog(Page) pagination

### ISSUE THREAD

**Issue by vinzscam** [backstage/backstage#12247]
Today adopters with 5k+ might encounter issues when viewing the `/catalog` page.
The issues are related to how the entities are fetched by the frontend. By default (almost) all the entities present in the database are fetched and returned in one shot.
This means that in some cases the loading time of the CatalogPage is high. This issue has been pointed out by dozens of adopters. In some cases the issue wasn’t only affecting loading time of the CatalogPage, but has affected the entire usability of the UI. Since a lot of UI components depend on having all the entities downloaded and available in the frontend, in some cases the UI freezes or becomes unresponsive.

In order to fix the issue mentioned above, pagination on the catalog’s entities needs to be enforced.
At the moment, the entities are fetched from the `GET /entities` endpoint, which returns an array of results.
The endpoint supports offset pagination, meaning that on each request, it is possible to provide offset, limit and cursor.
However, whenever a request is sent, only the array of results is sent back to the caller, while all the pagination data gets discarded. Due to this limitation, it is not possible to send subsequent requests to the same endpoint, meaning that it isn’t possible to use pagination.

Having a fully supported paginated endpoint is crucial to provide a good user experience of the CatalogPage.

## Proposed solution

In order to not introduce breaking changes to the current endpoint, I propose to create a new version of the `/entities` endpoint which returns a paginated response of the entities.

I’ve been investigating the proposed solution and I came to a conclusion: this wouldn’t be enough.

Unfortunately, during the years, a lot of logic has been built on top of the CatalogPage.
As a result, a lot of filters depend on having all the entities available on the frontend in order to work properly.
So, together with the new endpoint, *all the frontend filters need to be rebuilt*.
Some of them were fairly easy to fix, like owners, lifecycle and tags.
Others, like starred or owned entities, were a bit more complicated.

During the last (6) months I’ve been working on this and I reached out to a good solution, proving that it is possible to make the CatalogPage work with 30k+ entities.

The amount of work has been massive. However I think it is possible to split the work into small pull requests, in order to ship this as soon as possible.

I will use this issue to track the work that needs to be done, in order to implement a better Catalog Page.

- [x] Create new paginated entities endpoint #12246
- [ ] Decoupling filters from having all the entities available in the frontend
  - [x] EntityOwnerPicker: #17514
  - [x] EntityProcessingStatusPicker: #17889
  - [x] EntityLifecyclePicker: #17888
  - [x] EntityOwnerPicker: #17514, #18199
  - [x] UserListPicker: #20339
- [ ] Frontend pagination
  - [x] Build pagination on top of EntityListProvider and DefaultCatalogPage:  #21202
  - [ ] DI frontend support for pagination
  - [ ] Server side search in `PaginatedCatalogTable`: #22131
  - [ ] (Single) column server side sorting in `PaginatedCatalogTable`

Below some extra features we can support once the above issues are done:
- [ ] Sort by multiple column Backend support: #17600
- [ ] Multiple columns server side sorting in `PaginatedCatalogTable`

https://user-images.githubusercontent.com/8433119/175358148-dcac96a3-a0bf-4573-91ef-d5d6734768ca.mov

**Comment by freben** [comment]
> In order to fix the issue mentioned above, pagination on the catalog’s entities needs to be enforced.

Maybe not enforced, but at least better supported. _Enforcing_ is more a matter of protecting the backend than enabling the proposed frontend speedups.

> At the moment, the entities are fetched from the `GET /entities` endpoint, which returns an array of results. The endpoint supports offset pagination, meaning that on each request, it is possible to provide offset, limit and cursor. However, whenever a request is sent, only the array of results is sent back to the caller, while all the pagination data gets discarded. Due to this limitation, it is not possible to send subsequent requests to the same endpoint, meaning that it isn’t possible to use pagination.

Not quite accurate.

- It does support two different pagination methods: offset/limit, and cursor based.
- The cursor based one happens to at this point be implemented _in terms of_ offset/limit under the hood as a shortcut, but that's opaque to the user; if we made it smarter under the hood nothing would have to change from the calling side
- Pagination info _is_ actually returned in the response, but [in terms of a `Link` response header](https://github.com/backstage/backstage/blob/801d606909605fb0fd3f85854435992e481321ad/plugins/catalog-backend/src/service/createRouter.ts#L120), not in the body - so callers can absolutely perform pagination already today, with both methods

> Having a fully supported paginated endpoint is crucial to provide a good user experience of the CatalogPage.

Yep indeed but it's so far been more about how capable the filtering and sorting is.

Let me also add one intermediate step that I've mentioned in the past. Instead of going the full way to getting the perfect situation in place where the backend can mirror the filter state and get precisely one ideal page... The frontend could "stream" in data by issuing a number of paginated backend requests, filling up an internal buffer until there's enough data to show just the first page in the frontend. When client filtering has been applied, maybe it had to load 200 entities from the backend in two 100-entity pages until it had the requisite 20 _matching_ ones to display. Then it sends that to the table, which has a much, much smaller amount of data to process and bother React with. Then when the user goes to page two, we stream in more pages until we have 40 matching ones to display, etc. This solution is obviously not perfect when there are very very few or even zero matches, because we have to make a lot of backend requests still. But those will at least be using all of the backend-capable filters (e.g. kind matching); it's only the client-only filters that have to be applied afterwards.

**Comment by jinnjwu** [comment]
any progress of this issue

**Comment by lalit774** [comment]
any progress of this issue

**Comment by benjdlambert** [comment]
We're looking at merging on of the pieces of this here: https://github.com/backstage/backstage/pull/12246

**Comment by efenner-cambia** [comment]
Is this done yet? I know work was happening on it up above, but it looks like this was auto-closed rather than properly closed

**Comment by vinzscam** [comment]
work happening as we speak 😄

**Comment by drodil** [comment]
Surprisingly: any progress of this issue 🤔😄

**Comment by vinzscam** [comment]
> Surprisingly: any progress of this issue 🤔😄

progress are tracked in some checkboxes at the end of the description 😄

**Comment by sfatzinger** [comment]
Bump: Very interested in this

**Comment by freben** [comment]
Yeah the catalog frontend still isn't properly leveraging the backend's pagination capabilities. Essentially it still calls the old APIs that were there before pagination support was added

**Comment by ck9891** [comment]
Any updates on this one? My catalog page is almost unusable at times because of this issue.

**Comment by freben** [comment]
I believe this was fixed by #21202 but it needs a prop to be added to the page at this point. See https://backstage.io/docs/releases/v1.21.0#catalog-pagination

**Comment by freben** [comment]
Oh sorry there may have been some follow-up actions left at the top still - reopening

**Comment by riginoommen** [comment]
Count insights of the records should be enabled also

**Comment by sfatzinger** [comment]
Is there a plan to think about / work on server side sorting?

**Comment by vinzscam** [comment]
> Is there a plan to think about / work on server side sorting?

Server side sorting is done backend side. What is currently missing is the ability to sort entities properly when clicking on a column of `CatalogTable`.

**Comment by bsiedleckiallegro** [comment]
catalog title does not work for `mode: offset` on 1.34.2 :(
