### ISSUE TITLE
[Backend System] Build out Services

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#13083]
## Backend System Info

- [RFC](https://github.com/backstage/backstage/issues/11611)
- [Overview Issue](https://github.com/backstage/backstage/issues/13081)
- [Milestone](https://github.com/backstage/backstage/milestone/36)

## Service Tasks

Tasks related to building out service definitions and implementations.

- [x] Service corresponding to app-backend is missing, may need new capabilities added to the backend-app-api? Implement the possibility to configure a single root fallback? I.e. /* -> /api/app/*
- [x] Logger: Winston “compatible” BS Logging implementation or winston directly, research pros/cons, #15245
- [x] Cache
- [x] Database
- [x] Config - if we want more methods we'll extend the interface
- [x] Discovery
- [x] HttpRouter
  - [x] Figure out how to handle root middlewares and middleware configuration in general. Might be an additional root scoped http service, or some other solution. Exploration ongoing in `mob/root-http-service-experiments`, #15462
- [x] Permissions
- [x] Scheduler
- [x] ~UrlReader® - needs easier configuration methods~~
- [x] Suffix all service interface definitions with `*Service`, #15237
- [x] Move all helpers that we want to deprecate to `backend-common`, for example `loggerToWinstonLogger`
  - [x] `loggerToWinstonLogger`, #15529
- [x] Remove `backend-common` dependency from `backend-plugin-api`
- [ ] Potentially rename some core services with a `Legacy*` prefix for the ones we want to replace?

### Low priority tasks

- [ ] Deprecation path for `@backstage/backend-common`, needs replacement:
    - [ ] Context
    - [ ] Discovery #20280
    - [x] Logging #15688
    - [ ] Middleware
    - [ ] Reading
    - [ ] Scm
    - [x] Service #15589
    - [ ] Tokens
    - [ ] ContainerRunner
    - [ ] Other utils
    - [x] Config loading #15688
    - [ ] Path/URL utils -> maybe move to backend-plugin-api?
- [ ] FetchService
- [ ] Remove `backend-common` dependency from `backend-app-api`
  - [x] createServiceBuilder #15589
  - [x] loadBackendConfig #15688
  - [ ] CacheManager
  - [ ] DatabaseManager
  - [ ] DatabaseManager
  - [x] createRootLogger #15688
  - [ ] ServerTokenManager
  - [ ] UrlReaders
- [x] Explore options for accessing services in service factory options, i.e. meta factories
- [ ] New or evolved services
  - [ ] Metrics service + exporter and configuration of views
  - [ ] Explore options for decoupling DatabaseService from Knex
  - [ ] TokenManager - tweak to handle all kind of identities? Authentication Header Standardization both for producing and consuming the Backstage Token with the claims.

**Comment by taras** [comment]
**Options for other ORMs**

* https://github.com/drizzle-team/drizzle-orm
* https://www.prisma.io/
* https://github.com/kysely-org/kysely

**Comment by efenner-cambia** [comment]
@Rugvip Should this have been allowed to close?

**Comment by efenner-cambia** [comment]
bump

**Comment by camilaibs** [comment]
Closing in favor of https://github.com/backstage/backstage/issues/24493
