### ISSUE TITLE
[Backend System] Core API

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#13082]
## Backend System Info

- [RFC](https://github.com/backstage/backstage/issues/11611)
- [Overview Issue](https://github.com/backstage/backstage/issues/13081)
- [Milestone](https://github.com/backstage/backstage/milestone/36)

## Core API Tasks

Tasks related to the Core API surface

- [x] @backstage/backend-defaults, #13085, #13078
- [x] Merge custom services with default services to be able to replace implementations. #13089, #13089
- [x] :busts_in_silhouette: Test utils, #13086, #13113
- [x] Optional module options parameter, `catalogModule({}) -> catalogModule()`, #13116
- [x]  Improve error messaging for any user errors in the core wiring, #13124
- [x] :busts_in_silhouette: Pattern for common overridable utilities outside of core, #13087, #13197
- [x] :busts_in_silhouette: Nice common way to provide options to services, when installing replacements in the app. For example `createBackend({ services: [httpRouter({ ...options })] })` <- what could httpRouter be here? Need some form of higher order factory that accepts options #13510
- [x] Naming bikeshedding across the board, e.g. “registrable”, #13124
- [x] :busts_in_silhouette: Shared Environment Definitions, #13088, #15743
- [x] Figure out how to get rid of hardcoded `'root'` in service factories. #13618
- [x] Nice and clear errors for when ServiceRefs aren't available. At least needs a fix in `ServiceRegistry.ts` #13499
- [x] Possibility to stop backend, and add stopping to `startTestBackend` #14985
- [x] Populate `startTestBackend` with mock services.
  - [x] Make sure test backends don't conflict with each other, i.e. better mock root router service
- [x] Handle TypeScript 4.9 issue, which currently breaks the service factory API. Find workaround or wait for TS 5.0 and verify #15748
- [x] Fix options declared with `interface` being passed to `createBackendPlugin`
- [x] Verify that current APIs show up nicely in docs
  - [x] Fixes for messy create methods #15522
  - [x] Fixes for noisy service factory types #15523
  - [x] Fixes for core services #15527
- [x] Root scoped services should always be initialized #15235
- [x] ~Figure out how to provide access to config during backend setup~ - skipping this for now
- [x] Throw error if user supplies service refs with duplicate IDs #15520
- [x] Explore options for smoother migration from old system
- [x] Add plugin compatibility wrapper that lets you use old plugin definitions in new system #15695
- [x] Export `mockServices` from `@backstage/backend-test-utils` to make it easier to write unit tests for backend atoms. #15774
- [x] Let’s replace our Webpack hot module reloads with something nicer, just gotta make sure we keep the state of SQLite somehow. #16103
- [x] Documentation for new backend system
  - [x] Initial structure #15801
  - [x] Core API and architecture docs #15963, #15915, #15909
  - [x] Document naming patterns #15866
  - [x] Document how to setup up a backend #15837
  - [x] Document how to build plugins & modules #15918
  - [x] Document how to write tests #15886
  - [x] Documentation for core services #15851
  - [x] Migration documentation for backends #15847
  - [x] Migration documentation for plugins #15826

### Followup tasks (revisit before stable)

- [x] Reconsider module initialization order. Should module init be called after plugin init?
  - Not making any change here right now. Anything interacting with an extension point or any other form of DI needs to be initialized before the thing consuming it. The solution in place right now is to use the lifecycle service in case one wants to do additional initialization after plugin startup.
- [x] Local development entrypoint? dev/backend.ts for backend setup perhaps? #19452 
- [x] Add checks at runtime to forbid forbidden things
  - [x] Forbid module access to extension points that are not registered on the target plugin. #19354 
  - [x] Forbid modules from registering extension points, #15957
  - [x] Forbid plugins from depending on extension points, #15957
- [x] Simplify backend initialization: For each plugin, initialize modules first, then the plugin. #17953 
- [ ] Support for seamless switching and mixing of environments for local development, e.g. using prod auth backend but local catalog one.
- [x] :busts_in_silhouette: Readiness checks across plugins to make sure they don't call each other too early
  - Don't want to do anything advanced here, it gets very complicated with horizontally scaled deployments. The root lifecycle service can already be used to wait for all plugins to be initialized.
- [x] Should we allow adding service factories with `backend.add()`? #19334 
- [ ] Investigate why in some cases the implementation type is inferred and not the service type, see [api-report](https://github.com/backstage/backstage/blob/36adf34/packages/backend-app-api/api-report.md?plain=1#L15)
- [ ] A CLI template for creating additional backend packages

**Comment by camilaibs** [comment]
Closing in favor of https://github.com/backstage/backstage/issues/24493
