### ISSUE TITLE
[Catalog] Expanding the "Extending the model" Documentation

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#14383]
## Suggestion

During one of the recent Catalog SIG meetings we discussed providing more documentation around the concepts found on the existing "[Extending the model](https://backstage.io/docs/features/software-catalog/extending-the-model)" documentation. The intention of this issue is to be able to track the work needed to expand this documentation with examples of how to actually make the changes needed.

## Tasks

- [ ] Adding a New Kind
- [ ] Adding New Fields to the Metadata Object
- [ ] Adding New Fields to the Spec Object of an Existing Kind
- [ ] Adding a New Relation Type
- [ ] Changing the Validation Rules for The Entity Envelope or Metadata Fields

## Context

We see regular requests for how to create new Kinds or add new Fields to the Spec or Metadata, etc. on Discord and GitHub. By expanding this documentation we can make it easier for people to make these types of changes following well thought out guidance.

**Comment by freben** [comment]
Assigning to me at least as a reminder!

**Comment by webark** [comment]
there are also a couple of the "TODO"'s around the KindValidator that could be good to fix before we solidify and prescribe the approach.

https://github.com/backstage/backstage/blob/f777433ab384196f44d454625a3d6c741c2915ef/plugins/scaffolder-common/src/TemplateEntityV1beta3.ts#L83-L88
https://github.com/backstage/backstage/blob/f777433ab384196f44d454625a3d6c741c2915ef/packages/catalog-model/src/kinds/util.ts#L20-L34

**Comment by KatharinaSick** [comment]
Hi,

I'm currently trying to add a new relation type for components, templates & resources (`createdBy`/`creatorOf`) and I just can't figure it out.  May I ask you to provide a short overview on how to do this? I already have a bit of experience with entity providers and processors so a very high level explanation would be enough I think. If you want, I could create a pull request with documentation about how to add a new relation type while implementing our new relation.

My current approach is to create an entity processor that checks for the `spec.createdBy` field and then creates a relation in the format described [here](https://backstage.io/docs/features/software-catalog/descriptor-format#common-to-all-kinds-relations). When setting the relation, Backstage throws an `Unknown field relations` error. This totally makes sense, but I can't figure out how to avoid this and link to the creating component. 
Further, my post processor has a type error because the `spec.createdBy` field is not known (which also makes sense but I don't know how to avoid it).

Thanks in advance for your help :)

**Comment by KatharinaSick** [comment]
I figured it out - If you want, I can prepare some documentation about how to add custom relations?

**Comment by Rugvip** [comment]
@KatharinaSick great! Did you base it on the [BuiltinKindsEntityProcessor.ts](https://github.com/backstage/backstage/blob/c010a30fe97147b925cc1ef4276291eb17c95169/plugins/catalog-backend/src/modules/core/BuiltinKindsEntityProcessor.ts#L108-L129)? Either way emitting relations is the way to go. If you have suggestions to make the docs more clear and informative that would be very welcomed! 🙏

**Comment by KatharinaSick** [comment]
Yep, I based it on the [BuiltinKindsEntityProcessor.ts](https://github.com/backstage/backstage/blob/c010a30fe97147b925cc1ef4276291eb17c95169/plugins/catalog-backend/src/modules/core/BuiltinKindsEntityProcessor.ts#L108-L129). I actually just wanted to add more documentation about adding custom relation types but when reading through the docs again, everything is quite clear already anyways :) I think I was just stupid two weeks ago - sorry for the unnecessary conversation.

**Comment by bluesk1d** [comment]
> Yep, I based it on the [BuiltinKindsEntityProcessor.ts](https://github.com/backstage/backstage/blob/c010a30fe97147b925cc1ef4276291eb17c95169/plugins/catalog-backend/src/modules/core/BuiltinKindsEntityProcessor.ts#L108-L129). I actually just wanted to add more documentation about adding custom relation types but when reading through the docs again, everything is quite clear already anyways :) I think I was just stupid two weeks ago - sorry for the unnecessary conversation.



> Yep, I based it on the [BuiltinKindsEntityProcessor.ts](https://github.com/backstage/backstage/blob/c010a30fe97147b925cc1ef4276291eb17c95169/plugins/catalog-backend/src/modules/core/BuiltinKindsEntityProcessor.ts#L108-L129). I actually just wanted to add more documentation about adding custom relation types but when reading through the docs again, everything is quite clear already anyways :) I think I was just stupid two weeks ago - sorry for the unnecessary conversation.

I'm still stupid so I could definitely use this documentation on actually _how_ to extend the model :)

**Comment by brunocascio** [comment]
> > Yep, I based it on the [BuiltinKindsEntityProcessor.ts](https://github.com/backstage/backstage/blob/c010a30fe97147b925cc1ef4276291eb17c95169/plugins/catalog-backend/src/modules/core/BuiltinKindsEntityProcessor.ts#L108-L129). I actually just wanted to add more documentation about adding custom relation types but when reading through the docs again, everything is quite clear already anyways :) I think I was just stupid two weeks ago - sorry for the unnecessary conversation.
> 
> I'm still stupid so I could definitely use this documentation on actually _how_ to extend the model and add a new relation :)
> 
> We're just starting with Backstage and looking to utilize it as a technology standards catalog/tech radar and it would be great to have a relationship that links a piece of tech (not a specific deployment) with an array of teams that currently use it. Something along the lines of consumerOf/consumedBy that can be applied to components

Check this plugin instead -> https://github.com/backstage/backstage/blob/master/plugins/catalog-graph/README.md

**Comment by bluesk1d** [comment]
> > > Yep, I based it on the [BuiltinKindsEntityProcessor.ts](https://github.com/backstage/backstage/blob/c010a30fe97147b925cc1ef4276291eb17c95169/plugins/catalog-backend/src/modules/core/BuiltinKindsEntityProcessor.ts#L108-L129). I actually just wanted to add more documentation about adding custom relation types but when reading through the docs again, everything is quite clear already anyways :) I think I was just stupid two weeks ago - sorry for the unnecessary conversation.
> > 
> > 
> > I'm still stupid so I could definitely use this documentation on actually _how_ to extend the model and add a new relation :)
> > We're just starting with Backstage and looking to utilize it as a technology standards catalog/tech radar and it would be great to have a relationship that links a piece of tech (not a specific deployment) with an array of teams that currently use it. Something along the lines of consumerOf/consumedBy that can be applied to components
> 
> Check this plugin instead -> https://github.com/backstage/backstage/blob/master/plugins/catalog-graph/README.md

Thanks! We actually do have that installed and dig it for visually representing the relations but we still need the new relationship to display.
