### ISSUE TITLE
📁 Catalog Improvement Meta Issue

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#14574]
### 🔖 Feature description

There are a lot of ideas around different ways that we can improve the Software Catalog. I've created this issue as a place to track all of these ideas at to make it easier to get an overview of what's already being discussed. It is also a place where we can synchronize the work between members of the community that want to help drive the catalog forward.

Please suggest things to add if you think that something is missing! 🙏 

## Model

- Better docs for extending the catalog: #14383
- There should be a more streamlined API for defining custom catalog models.
- Transitive relations: #7109

## Features

- Ingestion errors are hard to catch and need to be surfaced somehow.
- There is no good UX flow for moving or renaming entities
- Event-based catalog consumption: #8219
- Entity modification timestamps: #14181
- Multi-fetch: #12254, #14354
- Catalog federation: #4888
- Catalog onboarding page: #4741
- Entity statuses: #2292

## Ingestion

- Event-driven ingestion: #8232, #12155, #13931, #12156, #13575, #13531
- Ingestion UX: #11445
- Entity validation: #9245
- Refer to default branch: #9086
- Completely remove orphaned entities as a concept. Related: #7860
- Disallow entity deletions: #8616
- Disallow rogue locations: #13959
- Entity location deduplication: #14042

## Performance

- Catalog processing can be slow and not scale beyond a certain point
- Improved pagination: #12247, #12246
- Facets endpoint is slow: #13655
- Catalog is slow with large number of entities: #12829

## Bugs

- Provided entities not being deleted: #12883
- Unexpected sticky relations: #7872
- Conflicting entities are not detected: #10862

### 🎤 Context

.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by dtuite** [comment]
Excellent list @Rugvip .

Based on our experience rolling out Backstage with a few dozen customers, the items I'd highlight from your list are (in order)...

1.  Improved pagination (we estimate this will cut ~8 seconds (aka. 85%) off some page loads)
2. Ingestion errors are hard to catch and need to be surfaced somehow (seems like ~50% of customers ask "I can't see my component in the catalog..." at some point).
3. There is no good UX flow for moving or renaming entities (we get support tickets about this quite frequently)
4. Catalog onboarding page (yes but also... "I need to onboard 400 components... what do I do?")
5. Entity validation (helps to address all of the above points)
6. Completely remove orphaned entities as a concept (we've implemented our own garbage collection to work around this).

**Comment by taras** [comment]
@Rugvip we should add #14356 to the list as well

**Comment by angeliski** [comment]
I would love to see a more simple way to customize the entity pages/cards. 

I know isn't only the catalog, the core components should be get some benefits from this ideia, but I can imagine the big necessity comes from the catalog

Things like: add a new information from metadata, change some information from About. Add more information in tables and things like that. It's possible now, but is very difficult to achieve (from my "not React developer" point of view)

**Comment by Rugvip** [comment]
@afscrome that one is actually just about to be closed by #14584, does that solution cover your use-case as well? If not I think it might be best to outline the missing pieces in a new issue

**Comment by bforbis** [comment]
I'll also note that one of the issues I've seen is a lack of consistency in rendering Entity reference names in the UI.

On some pages like the top bar and in the graph, it gets rendered using `metadata.title` which is likely the best human readable option.

However in other cases, it gets rendered as just the `metadata.name` regardless of whether or not a title exists, like in parent/child links for groups, owner links on the catalog table view, and owner picker dropdowns in the scaffolder.

It seems like this really needs to be made consistent and should prefer `metadata.title` always to `metadata.name`. For my use case in particular, `metadata.name` uses uuids imported from other systems and often are not helpful at all to the end user.

**Comment by awanlin** [comment]
@bforbis, yeah, that for sure would be nice. As this is intended to be a meta-issue for all the related Catalog issues could you log an issue for this and then share the issue number here, please?

**Comment by bforbis** [comment]
@awanlin here you go:
https://github.com/backstage/backstage/issues/15965

**Comment by drodil** [comment]
Also, I would like to see an extendable stitcher as there are some cases where the same information comes from two different sources, for example, users might be ingested from multiple systems. Merging the entities should be possible so that metadata from system 1 can be combined with metadata from system 2. This though might be somewhat hard to do due to the async behavior of the providers. 

But especially the human-readable naming all over should be fixed by utilizing the metadata.title instead name.

**Comment by bforbis** [comment]
> There is no good UX flow for moving or renaming entities.

Is there an issue for this one yet? I'd like to see what has already been discussed.

**Comment by freben** [comment]
@bforbis Not really for exactly that, I don't think. There's been a number of reports of troubles with conflict resolution etc during moves, but no issue that comes immediately to mind that talks about specific remediations.

**Comment by knowacki23** [comment]
Hey everyone,
do you have any ideas about:
- [ ] Completely remove orphaned entities as a concept. Related: [#7860](https://github.com/backstage/backstage/issues/7860)

I'm asking because I would like to implement removing of orphaned entities.
@anisjonischkeit I've seen in [#7860](https://github.com/backstage/backstage/issues/7860) that you wanted to contribute to this one, do you have any updates on it?

Thanks! :smiley:

**Comment by drodil** [comment]
@knowacki23 might also be related to the upcoming debug tool that could potentially allow removing orphan entities from UI #9737

**Comment by knowacki23** [comment]
> @knowacki23 might also be related to the upcoming debug tool that could potentially allow removing orphan entities from UI #9737

From what I understand (please correct me if I'm wrong) this debug tool will add new view tab containing all the orphaned entities, I was hoping for a scheduled task like indexBuilder for the search engine, that will automatically remove non-existing entities from the catalog without any user interaction.

**Comment by Remyapraveen** [comment]
Hi team, I am not sure on the severity of this issue. Came across this on my newly built Backstage instance. The "Learn more about the Software Catalog" leads to a blank page in Backstage website. 


![image](https://user-images.githubusercontent.com/93478132/222136396-fc151f38-72d6-4047-ac14-c5d74e920ed9.png)



![image](https://user-images.githubusercontent.com/93478132/222136246-cd6fb4d6-8bfd-428f-8e5a-757fb9df4481.png)

**Comment by Rugvip** [comment]
@Remyapraveen thank you for reporting! We'll need to add a redirect to `https://backstage.io/docs/features/software-catalog/` in the [microsite config](https://github.com/backstage/backstage/blob/e539649d803e590a639fd78e4be0ebe1eef02007/microsite-next/docusaurus.config.js#L100). Do you want to submit a PR?

**Comment by Rugvip** [comment]
Turned out to be a pretty widespread issue. I ended up shipping it in #16708 through https://github.com/backstage/backstage/issues/14574#issuecomment-1453263180
