### ISSUE TITLE
🐛 Bug Report: Kubernetes plugin backend occasionally 504s

### ISSUE THREAD

**Issue by mclarke47** [backstage/backstage#18510]
### 📜 Description

Requests to the kubernetes plugin backend occasionally 504s instead of 200, it seems like some requests take longer than 10s and timeout

### 👍 Expected behavior

You should be able to configure the backend to extend the timeout beyond 10s for large queries

### 👎 Actual Behavior with Screenshots

`..."request":"POST /resources/workloads/query HTTP/1.1", "request_time":"9.999", "status":"504", "time_local":"30/Jun/2023:17:08:14 +0000"}`

`"POST /resources/workloads/query HTTP/1.1", "request_time":"10.001", "status":"504", "time_local":"30/Jun/2023:17:08:01 +0000"}`

`"request":"POST /resources/workloads/query HTTP/1.1", "request_time":"10.000", "status":"504", "time_local":"30/Jun/2023:16:31:10 +0000"}`

### 👟 Reproduction steps

None yet

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
```[tasklist]
### Tasks
- [ ] Better logging for which entities are timing out
- [ ] https://github.com/backstage/backstage/pull/18819
```

**Comment by mclarke47** [comment]
@hjpineda do you have any more details of this? I discovered my timeouts were unrelated

**Comment by tomasmota** [comment]
For anyone else running into this issue, make sure that your backend is actually able to reach the cluster. If it's not reachable, the backend will send 504. perhaps there should be a different error/status code for that case?
