### ISSUE TITLE
🐛 Bug Report: JsonValue cannot be assigned to ReactNode

### ISSUE THREAD

**Issue by RobotSail** [backstage/backstage#18654]
### 📜 Description

In React 18, the values being passed into TSX is expected to be assignable to ReactNode types.
In the current codebase, a lot of code still passes the JsonValue type directly into JSX. 
To properly complete the React 18 upgrade, we must convert this code to the types that we are expecting explicitly.

Here are the following files/packages that need to be fixed:

- [ ] **Techdocs plugin**: `plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx`
- [ ] **Search react**: `plugins/search-react/src/components/SearchResultGroup/SearchResultGroup.tsx`
- [ ] **Search react**: `plugins/search-react/src/components/SearchFilter/SearchFilter.Autocomplete.test.tsx`
- [ ] **Catalog React**: `plugins/catalog-react/src/components/InspectEntityDialog/components/OverviewPage.tsx`
- [ ] **Catalog React**: `plugins/catalog-react/src/components/EntityPeekAheadPopover/EntityPeekAheadPopover.tsx`
- [ ] **Catalog Import**: `plugins/catalog-import/src/components/StepReviewLocation/StepReviewLocation.tsx:131`
- [ ] **Catalog Import**: `plugins/catalog-import/src/components/ImportInfoCard/ImportInfoCard.tsx:63`
- [ ] **Catalog Import**: `plugins/catalog-import/src/components/DefaultImportPage/DefaultImportPage.tsx:57`

Currently this blocks #18243 

### 👍 Expected behavior

n/a

### 👎 Actual Behavior with Screenshots

n/a

### 👟 Reproduction steps

n/a

### 📃 Provide the context for the Bug.

n/a

### 🖥️ Your Environment

n/a

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
```[tasklist]
### Tasks
```

**Comment by vickywane** [comment]
Hello @RobotSail, 

I'm participating in the ongoing ZeroToMerge program at CNCF, and I would love to take this up as a part of my contribution to the program.

**Comment by vickywane** [comment]
Thank you very much for the update @RobotSail! 

I'm glad to know this is being fixed and yes, I still would love to contribute.
