### ISSUE TITLE
🚀 Feature: Add examples for every scaffolder action

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#18832]
### 🔖 Feature description

Each scaffolder action can be supplied with examples. It would be great for these examples to be complete to make it easier for writers of templates. 

### 🎤 Context

These examples appear in the installed actions page in the backstage ui. It allows the template writer a reference for what can be done with a template. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
```[tasklist]
### Tasks
- [x] confluence:transform:markdown
- [x] fetch:cookiecutter
- [x] gitlab:group:ensureExists
- [x] gitlab:projectAccessToken:create
- [x] gitlab:projectDeployToken:create
- [x] gitlab:projectVariable:create
- [x] fetch:rails
- [x] sentry:project:create
- [x] run:yeoman
- [x] fs:delete
- [x] fs:rename
- [x] github:actions:dispatch
- [x] github:deployKey:create
- [x] github:environment:create
- [x] github:issues:label
- [x] github:repo:create
- [x] github:repo:push
- [x] github:webhook
- [x] publish:azure
- [x] publish:bitbucket
- [x] publish:bitbucketCloud
- [x] publish:bitbucketServer
- [x] publish:bitbucketServer:pull-request
- [x] publish:gerrit
- [x] publish:gerrit:review
- [x] publish:github:pull-request
- [x] publish:gitlab
- [x] publish:gitlab:merge-request
- [x] publish:github
```

**Comment by awanlin** [comment]
I've got a Draft PR for `confluence:transform:markdown` just need a bit of feedback 👍

**Comment by steff-petro** [comment]
@punkle I would be happy to contribute with some examples.

I can start with the file system actions:
- fs:delete
- fs:rename

Please let me know if doing these two is fine with you.

**Comment by freben** [comment]
@steff-petro i think it's basically all up for grabs, mentioning here that you're starting on something is great of course since it reduces risk of duplicate work

**Comment by kurtaking** [comment]
I plan to take a look at the GitHub actions.

**Comment by subash54** [comment]
@punkle  I would like to contribute to the publish: bitbucket action.

**Comment by subash54** [comment]
> PR
https://github.com/backstage/backstage/pull/19640

**Comment by MarcBuch** [comment]
I can contribute an example for `publish:azure`

**Comment by benjdlambert** [comment]
@MarcBuch nice! Go ahead :tada:

**Comment by Teemukoivumaa** [comment]
I can do the `github:issues:label`

**Comment by parmar-abhinav** [comment]
I can do the `github:deployKey:create`

**Comment by punkle** [comment]
@parmar-abhinav brilliant, thank you

**Comment by mondragonda** [comment]
Can I help with `sentry:project:create`?

**Comment by parmar-abhinav** [comment]
Hello @punkle @camilaibs,

I've added examples for some of the actions. I would greatly appreciate it if you could spare a few moments to review them. Your feedback will provide clear guidance on areas where I might be lacking, and your insights will motivate me to continue working on the remaining actions.

Thank you

**Comment by andym0457** [comment]
Hi All,

Would it be possible to get PR #20531 reviewed and receive feedback so I can address any comments?

Many Thanks,
Andy

**Comment by mondragonda** [comment]
Hi. Opened a PR for `sentry:project:create` action. #20622
I would appreciate your review when possible,
Diego

**Comment by BillyMichael** [comment]
Opened a PR for bitbucketCloud. #23840

**Comment by parmar-abhinav** [comment]
Hello @punkle @camilaibs,

Can you please help me from where I can take the screenshots of the scaffolder examples. Like many contributors have attached screenshots of the example in the PR description.

Thank you

**Comment by parmar-abhinav** [comment]
I can help with the publish:bitbucket

**Comment by punkle** [comment]
@parmar-abhinav here is the link on the backstage demo site https://demo.backstage.io/create/actions

**Comment by parmar-abhinav** [comment]
@punkle Added examples for 2 actions, Can you please review the PR's.
https://github.com/backstage/backstage/pull/23989
https://github.com/backstage/backstage/pull/24005

**Comment by JeevaRamanathan** [comment]
I can do `gitlab:projectVariable:create`

**Comment by benjdlambert** [comment]
I think that all these are now complete, closing this issue! Thanks for all the help :tada:
