### ISSUE TITLE
[Meta] Frontend System MVP

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#19545]
## Goal
Get the Frontend System to a point where we can recommend that OSS users migrate their plugins to the new system.

## 💡 Soft Goals
These are non-functional requirements that we should keep in mind when designing the system.

- Dev experience is the same, yarn dev -> make changes
- Development experience is not confusing
  - Avoid simple mistakes like not exporting as default
  - The extension structure is clear and transparent
  - The architecture is easy to understand
  - The core APIs are easy to understand

## ✅ Tasklists

```[tasklist]
### MVP Release
- [x] Plugin
- [ ] https://github.com/backstage/backstage/issues/25207
- [ ] https://github.com/backstage/backstage/issues/25663
- [ ] https://github.com/backstage/backstage/issues/25730
- [ ] https://github.com/backstage/backstage/issues/25753
- [ ] https://github.com/backstage/backstage/issues/25785
- [ ] https://github.com/backstage/backstage/issues/25211
- [ ] https://github.com/backstage/backstage/issues/25665
- [ ] https://github.com/backstage/backstage/issues/25666
- [ ] https://github.com/backstage/backstage/issues/25667
- [ ] https://github.com/backstage/backstage/issues/25963
- [ ] https://github.com/backstage/backstage/issues/25964
- [ ] https://github.com/backstage/backstage/issues/25213
- [ ] App
- [ ] https://github.com/backstage/backstage/issues/25210
- [ ] https://github.com/backstage/backstage/issues/25216
- [ ] #24707
- [ ] https://github.com/backstage/backstage/issues/25218
- [ ] https://github.com/backstage/backstage/issues/25212
- [ ] https://github.com/backstage/backstage/issues/25208
- [ ] https://github.com/backstage/backstage/issues/25961
```

```[tasklist]
### Post MVP
- [ ] https://github.com/backstage/backstage/issues/25312
- [ ] https://github.com/backstage/backstage/issues/25214
- [ ] https://github.com/backstage/backstage/issues/25219
- [ ] https://github.com/backstage/backstage/issues/25215
- [ ] https://github.com/backstage/backstage/issues/25221
- [ ] https://github.com/backstage/backstage/issues/25222
- [ ] Default factories for Utility APIs?
- [ ] Revisit the need for cloning extensions or allowing multiple parents
- [ ] Revisit the ability for plugins to act as extension instances and have configuration
- [ ] Revisit "Unactionable things that can only be answered by time"
- [ ] https://github.com/backstage/backstage/issues/25664
- [ ] Dev utils for building isolated plugin apps
- [ ] Highlight possible plugins/routes when invalid route binding configuration is detected?
- [ ] Add templates for new frontend system to CLI
- [ ] Release candidate for entity pages
- [ ] Release candidate for sidebar
```

```[tasklist]
### Plugin Migrations / Extension Migrations
- [ ] Adopters can gradually migrate catalog entity pages
```

```[tasklist]
### Other TODOs
```

```[tasklist]
### Open Questions
- [ ] Should we remove things like `createApiFactory` and `createTranslationResource` and use extensions directly instead?
- [ ] Do we really need to have configurable attachment points?
- [ ] Replace `createRoot()` with `render(htmlEl)`?
- [ ] Should extensions declare optional inputs for configurable features, or immediately extract that functionality into a separate extension?
- [ ] Can we provide built-in migrations of extension config in order to simplify breaking changes to config?
- [ ] Could we lint for or otherwise ensure correct usage of route refs? e.g. making you're they're assigned to some extension in the plugin https://github.com/backstage/backstage/pull/22164#discussion_r1453125645
- [ ] Many of the app wiring errors should be demoted to warnings, although still be errors in tests. How do we surface those warnings in the app
- [ ] Could we allow for API Refs and maybe other similar refs to defined "old IDs"? making it possible to switch out the ID of a ref while still having it be associated with any of the previous ones.
- [ ] Should we provide some form of wrapper that makes it possible to export standalone components but still have them wrapped up with the appropriate plugin context for analytics etc.?
- [ ] Should we add an attachment point abstraction that serves as an indirection between extension attachments? Allowing for a many-to-many attachment relations with a fixed set of data.
- [ ] Can we fix the conflict where our naming convention for API extensions is the same for the local variables for those APIs within API factories? https://github.com/backstage/backstage/pull/24088#discussion_r1556020509
- [ ] Should attachTo be optional for blueprints?
```

<details>
<summary>Previous Issue Contents</summary>

## Alpha Improvements

Improvements to be made in response to feedback on the Alpha release.

### :shipit: Required for Stable Release

- [ ] **[breaking]** Simplify the creation of new extension types
- [ ] **[breaking]** TypeScript API for configuring, overriding, and decorating extensions
- [ ] **[breaking]** Revisit `createExtensionTester` - especially something that lets you wire extensions together
- [ ] Fully implement `compatWrapper` #22113 
- [ ] Add support for public sign-in page for protected frontends
- [ ] Design review of component refs
- [ ] Split `frontend-app-api` to `frontend-defaults` - remove MUI dependency
- [x] Improve error messaging on failed instantiation of extensions when there is a data ref input/output mismatch
- [x] Remove the `plugin.` prefix from route binding configs
- [x] Add default targets for external route refs
  - [x] Backport to old frontend system
  - [ ] Make optional external routes the only option, forcing plugins to handle missing route bindings
- [ ] Figure out how to manage app icons - probably icon bundle extensions?
- [x] Hard errors when convertLegacyApp fails to identify elements, instead of silent ignore
- [ ] Adopters can gradually migrate catalog entity pages
- [x] Fix routing with path prefix https://github.com/backstage/backstage/issues/23709

### 🤔 Nice to Have

- [ ] Try to remove the `routable` prop from `ExtensionBoundary`
- [ ] Should ComponentRefs provide their own default component?
- [ ] Let extension overrides provide more metadata
- [ ] Flatten extension APIs
- [ ] Make sure Utility APIs exports are still sound
- [ ] Default factories for Utility APIs?
- [ ] Revisit `renderInTestApp`
- [ ] Revisit `createExtensionOverrides` naming
- [ ] Revisit the need for cloning extensions or allowing multiple parents
- [ ] Revisit the ability for plugins to act as extension instances and have inputs
- [ ] Revisit "Unactionable things that can only be answered by time"

## ✨Qs for Polish

Accepted items have been move to the "Alpha Improvements" section above.

#### New

- [ ] Could we lint for or otherwise ensure correct usage of route refs? e.g. making you're they're assigned to some extension in the plugin ([context](https://github.com/backstage/backstage/pull/22164#discussion_r1453125645))
- [ ] Can we completely remove the need for frontend `app-config.yaml`? relying fully on extension config and a few build-time variables instead?
- [ ] We probably want to highlight possible plugins/routes when invalid route binding configuration is detected?
- [ ] Many of the app wiring errors should be demoted to warnings, although still be errors in tests. How do we surface those warnings in the app?
- [ ] Should all route refs be optional? Leaving it to plugins to always provide a fallback for if the target route ref is not bound.
- [ ] Could we allow for API Refs and maybe other similar refs to defined "old IDs"? making it possible to switch out the ID of a ref while still having it be associated with any of the previous ones.
- [ ] Should be provide some form of wrapper that makes it possible to export standalone components but still have them wrapped up with the appropriate plugin context for analytics etc.?
- [ ] Should we add an attachment point abstraction that serves as an indirection between extension attachments? Allowing for a many-to-many attachment relations with a fixed set of data.
- [ ] How can we make sure that DOM layout is decoupled from the extension structure, so that extensions can be overridden with minimal risk of messing up layout?
- [ ] Can we fix the conflict where our naming convention for API extensions is the same for the local variables for those APIs within API factories? - [context](https://github.com/backstage/backstage/pull/24088#discussion_r1556020509)

#### Open

- [ ] Should we remove things like `createApiFactory` and `createTranslationResource` and use extensions directly instead?
- [ ] Should we more strongly encourage lazy loading of extension data? For example should `coreExtensionData.lazyReactElement` exist?
- [ ] Do we really need to have configurable attachment points?
- [ ] Replace `createRoot()` with `render(htmlEl)`?
- [ ] Should extensions declare optional inputs for configurable features, or immediately extract that functionality into a separate extension?
- [ ] Could we provide scoped extension creators for specific extension attachments? For example `RootExtension.createRouter`
- [ ] Do we need to provide additional tooling for a good local `dev/` experience?
- [ ] Can we provide built-it migrations of extension config in order to simplify breaking changes to config?

#### Handled

- [x] Try to revisit higher order extension creator factory, can we make it work?
- [x] Should we switch `createExtensionTester` to single options object form instead? 
- [x] Can we remove the `routable` prop from `ExtensionBoundary`?
- [x] ~Should `node.edges.attachments` be renamed to `node.edges.resolvedInputs`?~ - No
- [x] Should ComponentRefs provide their own simple default component? - makes it easy to guarantee presence in tests.
- [x] ~Should `configLoader` be something like earlyLoader instead?~
- [x] Add builtin extensions as an option to `createSpecializedApp`?
- [x] Move `createApp` to `frontend-defaults`, along with built-in extensions?
- [x] Could extension overrides provide more metadata to track where extensions have been installed from?
- [x] How can we make it easier to extend config schemas in extension creators?
- [x] Should we really have all core APIs in frontend-plugin-api?
- [x] Should we rename `renderInTestApp`?
- [x] Should we rename `compatWrapper`?
- [x] Should the `plugin.` prefix be removed from the IDs used for route bindings in config?
- [x] Should we rename `createPlugin` to `createFrontendPlugin`?
- [x] Should extension types be packaged a bit differently, for example `PageExtension.create()` rather than `createPageExtension`? That would allow for more functionality to be exposed more directly tied to the extension type.
- [x] Should we add some form of helper component for using app icons? something like `<AppIcon id='kind:api' fallback={KindApiSystemIcon}/>`? https://github.com/backstage/backstage/pull/22892
- [x] Could we have all ordered extensions enabled and listed in load order by default, but have the ones mentioned in config be reorder to the front? https://github.com/backstage/backstage/pull/24654

## 🤷  Low Priority / Out of Scope / Later

- [ ] An integrator can find documentation for each individual extension
- [ ] Automatically generate documentation for plugins
- [ ] Dev utils for building isolated plugin apps
- [x] Runtime API for introspecting the app
- [ ] Runtime API for mutating app extension structure
- [ ] Should we enable react-router data loader APIs? #19681

## 🧪  Alpha Milestone Tasks

- [ ] Users can build apps and plugins with support from documentation (~7)
  - [ ] Getting started guide - building from scratch, using legacy plugins
  - [ ] Architecture docs - understanding the system
  - [ ] Migration guides - migrating existing apps, plugins
  - [ ] Naming patterns - actual decision on naming patterns tracked separately
- [x] Adopters can migrate their existing app gradually (~4)
  - [x] ~Example-app uses legacy base with DI adapters~
  - [x] ~Create an API that lets you inject DI into existing apps - working assumption is that this is enough~
  - [x] Create an API that lets you inject existing apps into DI - replaces the above #20646 #20672
  - [ ] ~Adopters can gradually migrate catalog entity pages~
- [x] Adopters can use legacy plugins in DI through adapters (~8)
  - [ ] ~App-next uses DI base with legacy adapters~
  - [x] Create a legacy adapter that is able to take an existing extension tree
- [x] Entity pages can be constructed through DI, with very basic layout of cards (~3) #19545
  - See if it’s useful after initial spike - decide on whether to ship later
  - [x] Entity page cards and content are filtered
- [x] ~Integrators can configure permissions for extensions~ (~2)
  - Spike, find some options, might not implement the entire thing
  - The current assumption is that this is not needed, or that it can be implemented using a single route permission.
- [x] Make child extension IDs available on inputs
- [x] An integrator can configure or replace the sign-in page (~2)
- [x] Sidebar is configured through JSX like in existing apps (~1)
  - More or less done, but needs example + docs
- [x] Tests for all aspects of DI are easy to write, thanks to our testing utilities (~3)
  - [x] Migrate over relevant bits from test-utils to frontend-test-utils
  - [x] Ported: renderInTestApp, TestApiProvider
  - [x] Utility for testing extensions directly, renderTestExtension? - timeboxed
- [x] Fixes for known devex issues (~2)
  - [x] Hidden API for JSON dump of extension structure #20358
  - [x] Revisit the ‘at: …’ option #20438
- [x] Naming patterns for all parts of the system are established and documented (~3)
  - [x] Extension IDs - relation to package names and plugin IDs, etc.
  - [x] Extension ID hierarchy
  - [x] Extension export symbol
  - [x] Extension data IDs
  - [x] Input names
- [x] Close all API gaps against old system, tracked below (~?)

## 🚧  ~API Gaps~
- [x] Core-plugin-api
  - [x] Move over all API definitions and ApiRefs
  - [x] Move over AnalyticsContext
  - [x] Move over Any* helper types
  - [x] Forklift Utility API system, maybe skip withApis?
  - [x] Move over useApp + friends, trim away components that should not be used by plugins
  - [x] Do not move over anything related to legacy extension system, e.g. createComponentExtension, plugin.provide, Extension, attachComponentData, getComponentData
  - [x] Forklift routing system pieces, maybe skip some of the helper types like OptionalParams? Make them @ignore’d? #20574
  - [x] Do NOT move over ElementCollection, useElementFilter
  - [x] Move over translationApi, make it possible to configure through extensions
  - [x] Feature flags
  - [x] Route bindings #20574
  - [x] App components
- [x] Core-app-api
  - [x] Migrate AppComponents configuration to extensions
  - [ ] ~Figure out how to do icons - maybe not alpha though, the configuration part, what do we do with IconComponent?~

## ✅  ~Initial Tasks~

Initial tasks driving the creation of the first experimental version of the evolved frontend system in `@backstage/frontend-app-api` and `@backstage/frontend-plugin-api`.

- [x] Implement config schema and validation for extensions, likely using zod #19546
- [x] Add support for toggling extension instances #19550
- [x] Make sure all of the configuration shorthands work as expected, with tests #19551
- [x] Create higher level APIs for creating a few standard extensions, along with a higher-order helper for creating those #19646
- [x] Marge extensions and extension instances into a single extension concept #19669
- [x] ~Figure out how to resolve configured extension ref to a runtime value~ - no longer needed
- [x] Devise a method to connect extensions to an individual plugin #19768
- [x] Optional extension data inputs and outputs #19785
- [x] Switch to using default exports for package discovery #19818 
- [x] Settle package naming #19834
- [x] Consider moving core `reactComponent` extension data type to instead be `reactElement` #19919
- [x] Validate extension instances in createApp, disallow cycles or overriding root #20032
- [x] Validate extensions inputs and outputs at runtime in createApp #19937
- [x] Figure out how routing works in the new system, do we keep RouteRefs and useRouteRef? #19769
- [x] Fully implement createApp in frontend-app-api, avoiding the need for a core-app-api dependency #19850

</details>

**Comment by Rugvip** [comment]
First a quick glossary for some important terms:
  - **plugin**: A plugin instance created with `createPlugin` from either of our APIs
  - **plugin code**: The actual implementation of React components and APIs, which will be calling our APIs

---

As part of #20574 if found a strategy that I think is a good general path forward for building the new `frontend-*-api` packages alongside support for the existing `core-*-api` ones.

There are two important aspects of this compatibility:
  - Plugins built using `core-plugin-api` work within apps created with `frontend-app-api`.
  - Plugin code that uses `core-plugin-api` works within plugins created with the `frontend-plugin-api`.

In addition, there is a soft goal of having as little legacy compatibility code within the new `frontend-*-api` packages as possible. That way we avoid needing to maintain backwards compatibility within the new packages, letting us completely leave that behind in deprecated packages that we won't need to maintain in the long run.

With this in mind we can form a couple of constraints:

- Plugins built on top of `frontend-plugin-api` can only be installed in the new system. There may be backwards compatibility adapters, but those would be located outside of `frontend-plugin-api`
- Existing plugins built on top of `core-plugin-api` need to be possible to adapt for the new system. They key being that old plugin code built on top of older versions of `core-plugin-api` that is wrapped in a legacy adapter still need to function within an app built with `frontend-app-api`.

To achieve this I'm proposing the following strategy, split across three phases:

---

### Phase 1

During this phase the evolved frontend system is still in active development and we have not yet settled the APIs. This means that we need to keep compatibility with `frontend-*-api` away from `core-*-api`, with the exception of `/alpha` code.

Execution:

- No new plugins to be build on top of `frontend-plugin-api`
- These is no backwards compatibility code in `frontend-app-api` or `frontend-plugin-api`
- These is no forwards compatibility code in `core-plugin-api`
- Backwards and forwards compatibility is handled through a new `@backstage/core-compat-api` package
- Experimental implementations of the new system in existing plugins wrap the existing plugin code using helpers from `@backstage/core-compat-api` in order to have the old code support the new APIs.

---

### Phase 2

We reach this phase once the new system is stable enough that we can start adding support for it in the old `core-plugin-api` package. This will allow for plugin code to work seamlessly with both system.

- New plugins can start being built on top of only `frontend-plugin-api`, they will only be possible to use in the new system.
- These is no backwards compatibility code in `frontend-app-api` or `frontend-plugin-api`
- Forwards compatibility code is added to `core-plugin-api`. This makes it possible for existing plugin code to transparently support the new system. For example, `useRouteRef` from `core-plugin-api` is able to use both the new and old routing APIs simultaneously.
- Backwards compatibility is handled through `core-compat-api`. The forwards compatibility APIs remain in order to make it possible to adapt plugins using older versions of `core-plugin-api` that don't contain the forwards compatibility.
- Plugins implementing the new system no longer need to add wrap existing code with compatibility helpers, it'll work either way.

---

### Phase 3

This is the long-term future stable phase where all plugins are built using the new system and support for the old one is dropped.

- All new plugins are built using `frontend-plugin-api`
- These is no backwards compatibility code in `frontend-app-api` or `frontend-plugin-api`
- The `core-plugin-api`, `core-app-api`, and `core-compat-api` package are deprecated and removed from the main repo.
- Old plugins can still be adapted for the new system using the deprecated `core-compat-api` package.

**Comment by Rugvip** [comment]
For anyone interested in the current state of things: Our maintainer talk from KubeCon NA 2023 is now available on YouTube where we talk about this: https://youtu.be/ONMBYnhxnNU?t=437

**Comment by Rugvip** [comment]
Also #30001

**Comment by MihaiTabara** [comment]
@Rugvip can we close this?
