### ISSUE TITLE
[Azure DevOps Plugin] Multi-Org Support Meta Issue

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#19622]
## Description

This is a meta-issue to help track the tasks for implementing multi-org support in the Azure DevOps Plugin

Related issue: https://github.com/backstage/backstage/issues/10431

## Tasks

- [x] Provide an easy way to get the needed values from the various annotations (frontend) #19616 
- [x] Introduce a new annotation that contains the host and organization values (frontend) #19616 
- [x] Added support for using AzureDevOpsCredentialsProvider (backend) #20729 
- [x] Deprecate `azureDevOps.token` configuration value (backend) #20729
- [x] Update Azure Pipelines feature to use host and org (frontend and backend) #21595
- [x] Update Azure Repos feature to use host and org (frontend and backend) #21595
- [x] Update Azure Repos Git Tags feature to use host and org (frontend and backend) #21595
- [x] Update Azure Readme feature to use host and org (frontend and backend) #21595
- [ ] Update Azure Pull Request Dashboard feature to use host and org (frontend and backend)

## Nice To Have

- [x] Update the `AnnotateScmSlugEntityProcessor` to add the existing `dev.azure.com/project-repo` annotation  (this will hopefully be done by #19412)
- [x] Introduce a new `AzureDevOpsAnnotatorProcessor` to add both the `dev.azure.com/project-repo` annotation as well as the new `dev.azure.com/host-org` annotation #21565
- [ ] Deprecate the entire `azureDevOps` config and use a fall back based on the `integration.azure` configuration.

**Comment by dylanjustice** [comment]
@awanlin is there something I can do to help you with this effort? This would be a huge enhancement for our backstage instance.

**Comment by awanlin** [comment]
Hi @dylanjustice, right now I just need to get the reviews completed and merged for for https://github.com/backstage/backstage/pull/20729. Plan is to work on that this Friday again. Then I think we should be able to split up the work. How does that sound to you?

**Comment by dylanjustice** [comment]
Sounds good!

**Comment by awanlin** [comment]
Very, very, very, close to getting #20729 merged with a target of the `next` release coming this Tuesday November 28. I've also submitted #21565 that adds a new `AzureDevOpsAnnotatorProcessor` to add both the `dev.azure.com/project-repo ` annotation as well as the new `dev.azure.com/host-org` annotation making a lot easier to get the needed annotations in place 👍

**Comment by awanlin** [comment]
@dylanjustice it ended up being really easy for me to just finish this in one PR when I started. If you want to help test my Draft PR that would be great or look into how to get the Pull Request Dashboard to support multi-org that would be nice as well 👍

**Comment by dylanjustice** [comment]
> @dylanjustice it ended up being really easy for me to just finish this in one PR when I started. If you want to help test my Draft PR that would be great or look into how to get the Pull Request Dashboard to support multi-org that would be nice as well 👍

Just an FYI, I'm using a service principal for auth and the PR dashboard is working out of the box. I got the environment set up locally and everything is really smooth. API calls to the PRs and the pipelines is a little sluggish but that may be environmental. Not something I would be overly concerned about out of the gate.

**Comment by davidkarlsen** [comment]
@dylanjustice How are you able to use it with SP? I get 
```shell
Missing required config value at 'azureDevOps.token'
```
if I don't set the token and rely on the integration configuration (which uses SP)

**Comment by awanlin** [comment]
@davidkarlsen, for the time being the `azureDevOps` config is still needed as a fall back even though it will pick up the values from the `integration.azure` config. Eventually this will be deprecated but not at this time, there's a lot of existing users that will need to migrate slowly over

**Comment by awanlin** [comment]
As the work for this has been completed and shipped with the 1.21.0 release on December 19th - https://backstage.io/docs/releases/v1.21.0#azure-devops-multi-org-support - I'm going to close this issue. If you have any problems with this feature please log and new issue for it 👍
