### ISSUE TITLE
Umbrella Issue: CNCF Tech Doc Recommendations

### ISSUE THREAD

**Issue by dwelsch-esi** [backstage/backstage#21893]
### Umbrella issue

This is a checklist for the CNCF technical documentation analysis and implementation plan. It should be updated as sub-issues are added, completed, or otherwise modified.

### 🎤 Context

This issue is a recommended change resulting from an analysis of the Backstage documentation commissioned by CNCF. The analysis and supporting documents are here: https://github.com/cncf/techdocs/tree/main/assessments/0008-backstage

### Sub-issues

This is a list of issues representing the recommended work on the Backstage website and technical documentation.

#### Rewrite *Getting Started*

- [ ] https://github.com/backstage/backstage/issues/21828

Rewrite the *Getting Started* guides so they are task-oriented and point to specific user roles. Individual documents follow in separate issues. Use this issue to track revising of the table of contents. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by dwelsch-esi** [comment]
Please add the documentation label to this and all sub-issues.

**Comment by chlab** [comment]
I would be willing to help here if someone could tell me where to get started. I have contributed to the documentation [before](https://github.com/backstage/backstage/pull/21788).

**Comment by dwelsch-esi** [comment]
@chlab Happy to help. A good way to get started is to build the doc locally and tinker around with it. Instructions are [here](https://github.com/backstage/backstage/tree/master/microsite/README.md). 

Do you have any specific questions about this issue (or the sub-issues)? If not, I'd recommend looking through the sub-issues to find one that fits your interests and available time and going from there. If you'd like to discuss in Slack or Zoom, I'd be glad to do that too!

/cc @nate-double-u

**Comment by chlab** [comment]
@dwelsch-esi thanks for the hint, I was able to setup the doc locally. 
So what I understand is, that a big part of the audit finding are in the direction of restructuring the documentation by the role of the person reading it. Has there already been any work oder are there any ideas in restructuring the documentation into this new format? E.g. if I start work on #21942, adding a developer-focussed documentation under the _Getting Started_ section might be a bit out of place, no?

**Comment by Rugvip** [comment]
@chlab keep an eye on https://github.com/backstage/backstage/pull/23692 and the BEP coming out of it. It wasn't obvious exactly how we'd split the docs so the idea is to iron that out in that proposal

**Comment by dwelsch-esi** [comment]
@chlab I'm not exactly sure what you mean by a developer-focused workflow being out of place in the Getting Started section, but I think you might be asking if it would be wasted effort because the organization hasn't been settled yet? If that's your question, I can assure you that a developer-focused getting-started workflow will *not* be wasted effort. It needs to be written, regardless of where it eventually ends up in the documentation. It could possibly (even probably) be accessible from multiple points in the doc -- for example, from a "Getting Started" landing page that addresses all personas, and from the beginning of the Developer Guide. 

In the context of the BEP mentioned by @Rugvip, it seems logical that it would feature in the Portal documentation rather than the Framework doc. But there's no reason it couldn't be referenced from the Framework doc if necessary, for example from a discussion of how to set up an environment for testing plugin modifications.

**Comment by slamoree-expertsupport** [comment]
Added this sub-issue that's based on this umbrella issue: https://github.com/backstage/backstage/issues/29655.
