### ISSUE TITLE
🚀 Feature: Migrate New Scaffolder Modules to New Backend System

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#22214]
### 🔖 Feature description

We've started to break apart some of actions and functionality into modules like `@backstage/plugin-scaffolder-backend-module-gitlab` and `-github` etc, and right now these plugins are depended on by `@backstage/plugin-scaffolder-backend` to provide these actions out of the box.

### 🎤 Context

With the move to the new backend system, we will be dropping support that these things are installed out of the box, and that you will have to install the additional modules to get the additional behaviour, although it should be pretty seamless and simple to do.

### ✌️ Possible Implementation

These extra modules that we have created do not currently export a new Backend System Module, so we will need to create a module for each one of these packages that's exported from the package, which will take advantage of the `plugin-scaffolder-backend` extension point to register the actions automatically when it's installed.

```[tasklist]
### Tasks
- [x] `@backstage/plugin-scaffolder-backend-module-github`
- [x] `@backstage/plugin-scaffolder-backend-module-gitlab`
- [x] `@backstage/plugin-scaffolder-backend-module-bitbucket`
- [x] `@backstage/plugin-scaffolder-backend-module-gitea`
- [x] `@backstage/plugin-scaffolder-backend-module-gerrit`
- [x] `@backstage/plugin-scaffolder-backend-module-confluence-to-markdown`
- [x] `@backstage/plugin-scaffolder-backend-module-cookiecutter`
- [x] `@backstage/plugin-scaffolder-backend-module-rails`
- [x] `@backstage/plugin-scaffolder-backend-module-sentry`
- [x] `@backstage/plugin-scaffolder-backend-module-yeoman`
```
