### ISSUE TITLE
Feature: Edit Gitlab Issue (Scaffolder) Action

### ISSUE THREAD

**Issue by veenarm** [backstage/backstage#24905]
### 🔖 Feature description

This would add a function to edit a Gitlab Issue after it's been created. Allowing more granular modification processes.

### 🎤 Context

Gitlab currently doesn't allow 'non members' of projects to add/modify `labels` so when using a `token` for OAUTH the `createGitlabIssue` task fails to add/modify the labels.

My use case is have 2 tasks, the first task to create the issue using the `OIDC Token` of the user and then the next task `edits` the Issue to attach the required labels to the project. There may be other specific things you need at least a Gitlab `Reporter` access to.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
```[tasklist]
### Tasks
- [ ] https://github.com/backstage/backstage/pull/24938
```

**Comment by veenarm** [comment]
I've created the actions and starting work on the document side now for a PR.
