### ISSUE TITLE
Verify documentation coverage

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#25208]
```[tasklist]
### Tasks
- [ ] The entire system
- [ ] Default app extension tree
- [ ] An integrator can find documentation for each individual extension
- [ ] Migration guide
```
