### ISSUE TITLE
🚀 Feature: Allow Custom Cloudflare Header and Custom Cloudflare Cookie Key

### ISSUE THREAD

**Issue by jasondiazg** [backstage/backstage#25515]
### 🔖 Feature description

The [Cloudflare auth provider](https://backstage.io/docs/auth/cloudflare/provider/) should allow use custom `cf-access-jwt-assertion` header and the `CF_Authorization` cookie key.

### 🎤 Context

I have my backstage deployment protected by Cloudflare, however, my Cloudflare performs some custom internal workflows and as a result the `cf-access-jwt-assertion` header and the `CF_Authorization` cookie key are not present in the request that Backstage receive. The [Cloudflare auth provider](https://backstage.io/docs/auth/cloudflare/provider/) has the two values hardcoded, the header is harcoded [as constant](https://github.com/backstage/backstage/blob/master/plugins/auth-backend-module-cloudflare-access-provider/src/types.ts#L19) and the cookie key [directly in the function](https://github.com/backstage/backstage/blob/master/plugins/auth-backend-module-cloudflare-access-provider/src/helpers.ts#L71), both values should be configurables in the `auth.providers.cfaccess` section in the `app-config.yaml` file.

### ✌️ Possible Implementation

The Cloudflare auth provider should allow these two optional configurations `auth.providers.cfaccess.cfheader` and `auth.providers.cfaccess.cfcookiekey` in the `app-config.yaml`, if the values are not provided, then it should use the default ones (cf-access-jwt-assertion` and `CF_Authorization`).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
```[tasklist]
### Tasks
- [ ] https://github.com/backstage/backstage/pull/25516
```

**Comment by freben** [comment]
Sure! Makes sense, if that's configurable in the other end. Could the config fields perhaps be named `jwtHeaderName` and `authorizationCookieName`?

**Comment by jasondiazg** [comment]
> Sure! Makes sense, if that's configurable in the other end. Could the config fields perhaps be named `jwtHeaderName` and `authorizationCookieName`?

Hi @freben! Of course, let me change it.

**Comment by jasondiazg** [comment]
I already made the change and fix the tests, kindly take a look @freben @camilaibs #25516

**Comment by freben** [comment]
Fixed!
