### ISSUE TITLE
NFS: Moving the Scaffolder Plugin to NFS

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#26658]
```[tasklist]
### Tasks
- [ ] https://github.com/backstage/backstage/issues/26786
- [ ] https://github.com/backstage/backstage/issues/26785
- [ ] TemplateCardBlueprint or ComponentRef?
- [ ] TemplateListPageGroup extension to replacing `groups` prop
- [ ] TemplateListPageFilter extension to replace the `filter` prop
- [ ] `headerOptions` to be replaced with `componentRef` for header component, do we even need this? Can we use i18n?
- [ ] `defaultPreviewTemplate` to config instead
- [ ] `formProps` move to a `componentRef`
- [ ] What to do with `CustomLayouts`? Basically sets `ui:ObjectFieldTemplate` on the form, can we use the `componentRef` for form instead
- [ ] https://github.com/backstage/backstage/issues/25215
- [ ] Customization of the filters on the template list page - how do they relate to the catalog index page?
- [ ] Backwards compatibility with JSX way of configuring plugins. Establish patterns for re-use of components in both old and new systems.
```
