### ISSUE TITLE
🚀 Feature(scaffolder): Add `templateExecutePermission`

### ISSUE THREAD

**Issue by CptnFizzbin** [backstage/backstage#27742]
### 🔖 Feature description

With the current set of permissions, it's hard to filter the template list to ones that the user can actually run without also hiding them from the catalog as a whole. This feature adds a `scaffolder.template.execute' permission that policy writers can hook into to restrict who has access to a run a template.

This would also allow the template index page to dynamically filter templates to ones the user is actually able to run.

### 🎤 Context

At my company, we have some template actions that need to be restricted to a specific group, which can be done via the existing `actionExecutePermission`, however it still allows the user to attempt to run the template, but it just skips over those actions.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
```[tasklist]
### Tasks
- [x] add new permission and rules
- [ ] (optimization) fetch templates via scaffolder router instead of catalog
- [ ] https://github.com/backstage/backstage/pull/27748
```

**Comment by awanlin** [comment]
Please make sure to document this - https://backstage.io/docs/features/software-templates/authorizing-scaffolder-template-details - as this has created a large number of permissions you need to have just for a person to be able to run a template. 

Also, worth being aware of these changes and the discussion in the PR - https://github.com/backstage/backstage/pull/25969

**Comment by CptnFizzbin** [comment]
Yep, that's another part I'm hoping to resolve as well. Possibly by merging the existing permissions into the new one.

And thanks for the link to the other PR, i'll have a look

**Comment by CptnFizzbin** [comment]
Actually, that might be a good question to ask now:

Should the existing `templateParameterReadPermission` and `templateStepReadPermission` be deprecated in favour of a unified `templateExecutePermission`? What effects would that have?

**Comment by awanlin** [comment]
Might be worth bringing this up at the Framework SIG on the 26th and/or the Scaffolder SIG on the 29th. Calendar is here: https://calendar.google.com/calendar/u/0/embed?src=c_qup9gbhn9sqpuao6trttd8mk5s@group.calendar.google.com

This would help coordinate this better IMO.

**Comment by CptnFizzbin** [comment]
I'm not familiar with what the Framework or Scaffolder SIGs are.

**Comment by awanlin** [comment]
They a meetings for the community to attend that are specific for those areas - Special Interest Groups (SIG). Framework SIG covers the overall Backstage Framework and Scaffolder SIG is for the scaffolder and software templates. More details are here: https://github.com/backstage/community/tree/main/sigs

**Comment by CptnFizzbin** [comment]
PR now ready for review :)

**Comment by CptnFizzbin** [comment]
Notes from Framework SIG:
- Should the existing `stepRead` and `parameterRead` permissions be updated to restrict who can view a template
- Does this PR add too many conditions?

**Comment by CptnFizzbin** [comment]
> Does this PR add too many conditions?
The list of conditions added is the same as the ones for the existing permissions to allow for simplifying the permission check into one permission. There are a set of `hasBooleanProperty`, `hasStringProperty`, etc... conditions that are just variations on a generic `hasProperty` conditional

**Comment by CptnFizzbin** [comment]
#28494 is part of the implementation for this issue
