### ISSUE TITLE
Fill out missing or incomplete configuration schema

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3364]
## Feature Suggestion

#3264 added support for configuration schema along with mostly complete schemas for `@backstage/cli`, `@backstage/core`, and `@backstage/backend-common`. In addition the minimal required schema was also added for all frontend plugins to receive their required config.

We should fill the schema with descriptions and examples for the rest of all possible config values. The following packages are known to either be completely or partially missing config schema:

- [x] `packages/backend-common`
- [x] `plugins/auth-backend`
- [x] `plugins/catalog-backend` (#3739)
- [x] `plugins/cost-insights` (#3264)
- [x] `plugins/kubernetes-backend`
- [x] `plugins/proxy-backend`
- [x] `plugins/scaffolder-backend` (#3722)
- [x] `plugins/techdocs` (#3799)
- [x] `plugins/techdocs-backend` (#3799)
- [x] `plugins/sentry` (#3698)
- [x] `plugins/rollbar-backend` (#3404)
- [x] `plugins/sonarqube` (#3378)

## Possible Implementation

It's usually easiest to define schema using the `.d.ts` approach. To discover required schema it's best to browse the existing config YAMLs as well as search for usages for the config API within the packages.

## Context

#2854 #3367 #3366

**Comment by keshann93** [comment]
Hi @Rugvip I would like to take up this issue to complete the missing configuration schema

**Comment by freben** [comment]
@keshann93 Assigned!

**Comment by adamdmharvey** [comment]
Note for the checkmark for cost-insights, I think this was done as implemented here: https://github.com/backstage/backstage/pull/3264

**Comment by Rugvip** [comment]
@adamdmharvey alright, thanks!

Closing this as we've covered the list. There are perhaps some missing pieces here and there and much of it doesn't have documentation, but I think it's best to save documentation updates for when we actually have some place to display it! :grin:

Thank you @keshann93 for helping out with so many of these, and everyone else that helped out too! 🎉
