### ISSUE TITLE
[Composability] Meta Issue to track composability work

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3414]
We're starting the actual implementation of the ideas mentioned in https://github.com/backstage/backstage/issues/1536#issuecomment-729621634. We've divided it all up into a number of issues, listed below:

- [x] #3415 Internal node data
- [x] #3416 create*Extension
- [x] #3417 route path discovery
- [x] #3418 RouteRef mount points and global route ref association table
- [x] #3461 Plugin instance collection
- [x] #3419 useRouteRef
- [x] #3421 Plugin egress routing
- [x] #3530 createApp, createPlugin
- [x] #3422 Lazy loading
- [x] #3423 dev-util updates
- [x] #3424 plugin migrations
- [x] #3425 EntityFilter etc.
- [x] #3809 Documentation
- [x] Migrate `app`, `create-app` + migration guide
- [x] Update all other docs to only mention new system
- [ ] Remove deprecations

Some issues that we're hoping to address with this work:

- Much cleaner code in the app, and easier navigation and mapping of app code to routes and pages.
- Runtime sitemap, allowing us to build tooling that is aware of all top-level routes and other things that are registered at an app level.
- Error boundaries, making sure that errors within plugins generally stay within each plugin and don't break the app.
- Plugin contexts, allowing components used within the plugin to get more context about the plugin they're being used within.
- A compatibility boundary for bridging across different versions of Backstage, allowing older plugins to be mixed with new ones, etc.
- Lazy loading, intially just component, but down the line likely APIs as well. This significantly speeds up initial page load and is a necessity in any large Backstage app.
- Making RouteRefs work and be usable in more scenarios along with parameterized RouteRefs. This will allow for a much cleaner isolation between plugins while still being able to link between them when needed.

Some concrete things from previous discussions:

- Most of the initial composability ideas #1536
- Composability challenges in #2791
- Features left out of https://github.com/backstage/backstage/pull/2987#discussion_r510091741
- Some forms of deeper customization within plugins, for example https://github.com/backstage/backstage/issues/3348#issuecomment-731602988
- Future widget-like concepts as mentioned in chapter 4 of https://github.com/backstage/backstage/issues/1233#issue-636445287
