### ISSUE TITLE
[Composability] Port existing plugins to new plugin extensions API

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3424]
## Feature Suggestion

Migrate plugins to use the new plugin extensions API from #3416, starting with some of the standalone plugins that don't have any advanced composition patterns.

List of plugins to be migrated:

- [x] `plugin-api-docs` #4341
- [x] `plugin-catalog` #4356
- [x] `plugin-catalog-import` #4361
- [x] `plugin-circleci` #4365
- [x] `plugin-cloudbuild` #4365
- [x] `plugin-cost-insights` #4474
- [x] `plugin-explore` #4165 
- [x] `plugin-fossa` #4337
- [x] `plugin-gcp-projects` #4341
- [x] `plugin-github-actions` #4365
- [x] `plugin-gitops-profiles` #4395
- [x] `plugin-graphiql` #4342
- [x] `plugin-jenkins` #4365
- [x] `plugin-kafka` #4368
- [x] `plugin-kubernetes` #4368
- [x] `plugin-lighthose` #4361
- [x] `plugin-newrelic` #4368
- [x] `plugin-org` #4361
- [x] `plugin-pagerduty` #4395
- [x] `plugin-register-component` (deprecated) #4395
- [x] `plugin-rollbar` #4369
- [x] `plugin-scaffolder` #4346
- [x] `plugin-search` #4395
- [x] `plugin-sentry` #3843
- [x] `plugin-sonarqube` #4342
- [x] `plugin-tech-radar` #4474
- [x] `plugin-techdocs` #4395
- [x] `plugin-user-settings` #4341
- [x] `plugin-welcome`  #4342 

## Context

#3414

**Comment by Fox32** [comment]
@rugvip Maybe we should extend the "TBD" section in the issue entry above 😉 

Suggested content (edit my comment to copy the markdown):

- [ ] `plugin-api-docs`
- [ ] `plugin-catalog`
- [ ] `plugin-catalog-import`
- [ ] `plugin-circleci`
- [ ] `plugin-cloudbuild`
- [ ] `plugin-cost-insights`
- [ ] `plugin-explore` #4165 
- [ ] `plugin-fossa`
- [ ] `plugin-gcp-projects`
- [ ] `plugin-github-actions`
- [ ] `plugin-gitops-profiles`
- [ ] `plugin-graphiql`
- [ ] `plugin-jenkins`
- [ ] `plugin-kafka`
- [ ] `plugin-kubernetes`
- [ ] `plugin-lighthose`
- [ ] `plugin-newrelic`
- [ ] `plugin-org`
- [ ] `plugin-pagerduty`
- [ ] `plugin-pagerduty`
- [ ] `plugin-register-component` (deprecated)
- [ ] `plugin-rollbar`
- [ ] `plugin-scaffolder`
- [ ] `plugin-search`
- [x] `plugin-sentry` #3843 
- [ ] `plugin-sonarqube`
- [ ] `plugin-techdocs`
- [ ] `plugin-user-settings`
- [ ] `plugin-welcome`

After all plugins are migrated, we can migrate the example app itself.

**Comment by Rugvip** [comment]
@Fox32 Thanks!

**Comment by Rugvip** [comment]
Looking at `gcp-projects`, `api-docs`, and `user-settings`

**Comment by Fox32** [comment]
Having Sonarcloud and api-docs on my list, but maybe you can show how some stuff is done at api-docs. Sonarcloud is very similar to fossa

**Comment by Fox32** [comment]
Maybe closed to early? What about #4490?
