### ISSUE TITLE
Port date library usage over to use luxon

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#4278]
As per [adr010-luxon-date-library](https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr010-luxon-date-library.md) (discussed in #3401) we should convert existing usages of date libraries (e.g. `momentjs`, `dayjs`, etc.) over to use [luxon](https://moment.github.io/luxon/).

Usages of `moment.js`

  - [x] ~~`plugins/auth-backend` (#4386)~~
  - [x] ~~`plugins/catalog` (#4389)~~
  - [x] ~~`plugins/circleci` (#6022)~~
  - [x] ~~`plugins/cloudbuild` (#7140)~~
  - [x] ~~`plugins/cost-insights` (#6159)~~
  - [x] ~~`plugins/github-actions` (#6224)~~
  - [x] ~~`plugins/scaffolder` (#4606)~~
  
Usages of `day.js`

- [x] `plugins/circleci` (#7190)
- [x] ~~`plugins/cost-insights` (#6159)~~

Usages of `date-fns`

- [x] ~~`plugins/pagerduty` (#4478)~~

Other

- [x] ~~`plugins/sentry` (uses `timeago.js`) (#6021)~~

**Comment by nwright-nz** [comment]
I'll take a stab at this one!

**Comment by adamdmharvey** [comment]
Fantastic, thanks for the help @nwright-nz ! When you open a PR, if you can link back to this issue for tracking that would be great. Thanks so much!

**Comment by nilsstre** [comment]
Sorry, I missed @nwright-nz message, but I have created a PR for migrating the auth-backend plugin. #4386

**Comment by adamdmharvey** [comment]
@nwright-nz wanted to check in, how is this one going? Have you had any time to carve out to look into it, or should we open it to the community for further help?  Let us know!

**Comment by vcapretz** [comment]
hey, @andrewthauer @adamdmharvey I just opened a PR migrating the sentry plugin! 👍

please let me know if I missed something

**Comment by vannarath-poeu** [comment]
Hi @andrewthauer,

I created a PR for the cost-insights plugin. Please let me know if I missed out anything.

**Comment by HHogg** [comment]
Hey, 

I created a PR (#7140)  for the cloud build plugin. Please let me know if I missed anything or did anything incorrectly.

**Comment by HHogg** [comment]
I'm going to pick up the remaining CircleCI plugin now.

**Comment by HHogg** [comment]
PR created for the last plugin ☝️

**Comment by adamdmharvey** [comment]
WOW!  An effort across a large number of team members, both core and the community, and we seem to have met the ADR 🎉 🎉 👍🏻 

I triple checked, and the only references left in the raw code are a few package-lock elements, which infers they are being imported by being deps of ANOTHER 3rd party package. But the Backstage code itself involves no imports for these packages any longer.

Given this, I'm closing this issue and want to thank everyone who helped make this cleanup and alignment possible.  WAY TO GO TEAM!!!!!!!!
