### ISSUE TITLE
[Catalog] Meta Issue to track the work ongoing for the Catalog revamp

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#5165]
- [x] Implement the RefCounter
- [x] Implement the ProcessingStateManager
- [x] Implement the ProcessingStateDatabase
- [x] Implement the Stitcher
- [x] Split location handling in HighOrderOperations into a separate static location provider
- [x] Refactor LocationReader into CatalogProcessingOrchestrator
- [x] Refactor the rest of HigherOrderOperations into CatalogProcessingEngine
- [x] Implement orphan marking
- [x] Make location provider keep locations in sync with the processing state store
- [x] Implement user-triggered cascading deletions
- [x] MLP frontend orphan deletion flow
- [x] Endpoints for manual deletions of orphaned entities
- [x] Remove bootstrap location
- [x] _tests_
- [x] Capacity / performance validation - large entityprovider events, large individual location refreshes
- [x] Make stitcher update the search table
- [x] Error propagation
- [x] Filtering / paging / etc of entities
- [x] Make use of the Context for transactions
- [x] Switch master to use next catalog & release

Fixes #3750 
Fixes #3748  
Fixes #3749

**Comment by Fox32** [comment]
I wonder if #2001 is also part of this one (because it's marked as stale :wink)

**Comment by Rugvip** [comment]
@Fox32 yep! It will likely be closed by this work
