### ISSUE TITLE
Meta issue to track `backstage-cli install <plugin>` work

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#7422]
## Context

https://github.com/backstage/backstage/pull/7233 added an experimental `install` command to `backstage-cli` which can install plugins "automagically" in a Backstage app.

As of now, installing a plugin involves one or many of the following manual steps, which can be automated -

1. Install one or more frontend packages in a Backstage frontend app
2. Install one or many backend packages in a Backstage backend app
3. Add config to app-config.yaml
4. Add a frontend route to the plugin homepage
5. Add a backend route to the plugin
6. Add a tab on Catalog’s entity page
7. Add a sidebar item
8. Setup custom APIs (e.g. 
9. ...maybe more steps are needed to make a plugin work.

## Installation Steps

Any plugin can declare an `installationRecipe` in their `package.json` consisting of multiple "steps". A step can be as simple as printing a message into console or as complex as creating new files and importing things into App or Backend. [Example](https://github.com/backstage/backstage/blob/d9dde3129e13719cc62f3c7e30662a5b8d6af7db/plugins/graphiql/package.json#L64-L80)

Looking at all the plugins and their installation instructions, following "steps" can be created to be used in plugin installation recipes.

- [x] `message`: Logs a message in the console. (Implemented in https://github.com/backstage/backstage/pull/7233)
- [x] `app-route`: Add a new route to a Page component exported by a plugin. Updates `App.tsx` inside `packages/app/`. (Implemented in https://github.com/backstage/backstage/pull/7233)
- [ ] `app-config`: Add new configurations inside `app-config.yaml`. (Would be cool to use the app schema defined by the plugin to do so, instead of another duplicated custom definition). [Example](https://backstage.io/docs/features/kubernetes/configuration#configuring-kubernetes-clusters)
- [ ] `backend-route`: Add a new route to the plugin in the backend. [Example](https://backstage.io/docs/features/kubernetes/installation#adding-kubernetes-backend-plugin)
- [ ] `entity-page-tab`: Add a new tab in the Catalog's entity page. [Example](https://backstage.io/docs/features/kubernetes/installation#adding-the-kubernetes-frontend-plugin)
- [ ] `sidebar-item`: Add a new sidebar item in the frontend. [Example](https://github.com/backstage/backstage/tree/master/plugins/graphiql#installing-the-plugin)
- [ ] `setup-app-api`: Setup a custom API for a plugin. [Example](https://github.com/backstage/backstage/tree/master/plugins/graphiql#installing-the-plugin)

## `install` command features

- [x] Install the plugin's packages and update dependencies.
- [ ] Support backend plugins. Lookup `-backend` packages if frontend packages are not available for a plugin ID.
- [ ] Link to the corresponding backend plugin to be installed. Example (scenario): `backstage-cli install kubernetes` would install the plugin `@backstage/plugin-kubernetes`. It will find `@backstage/plugin-kubernetes-backend` listed in the `installationRecipe`. CLI would install the backend plugin as well as process the `installationRecipe` declared by it.

## 🧹 

- [ ] Documentation
  - [ ] Create a page with all the available steps that can be used in declaring installation recipes.
  - [ ] Describe the technical details of the install command and how it works.
  - [ ] Create a page describing how to create and test a new step
- [ ] Add installation recipes to plugins in this repository.
- [ ] Use installation recipes to dynamically generate plugin installation instructions in their README or microsite.

**Comment by ainhoaL** [comment]
Have a POC for `Link to the corresponding backend plugin to be installed.` by specifying peer plugin dependencies in the installation recipe. Will share soon after I tidy up the code!
