### ISSUE TITLE
Azure DevOps Plugin - Pull Request Dashboard

### ISSUE THREAD

**Issue by marleypowell** [backstage/backstage#7678]
A dashboard accessible from the sidebar to display Azure DevOps pull requests. This issue is to help track progress of tasks.

#### Frontend
- [x] Create pull request card component. #7897
- [x] Create pull request page. This will display "Created by me" and "Other PRs" columns. #7897
- [x] Implement long polling for PRs. #8282
- [x] Add ability to configure PR columns with parameters. #8384
- [x] Add the ability to resolve team and team member relations for PR column filters. #8517
- [ ] Add ability to reorder columns.
- [ ] Add ability to configure PR columns from the UI.
- [ ] Persist configured columns and their order.
- [ ] Add ability to select which azure devops projects to display PRs from.
- [ ] Display PR tags on the PullRequestCard.
- [ ] Implemented tooltips to add more useful information to the PullRequestCard.
- [ ] Add ability to configure different views.
- [ ] Investigate filtering by backstage teams.
- [ ] Pull Request Filter - Tags
- [ ] Add cache expiry to `PullRequestsDashboardProvider`. https://github.com/backstage/backstage/pull/8517#discussion_r773878421

#### Backend
- [x] Return a more detailed API response for pull requests. #8282

#### Other
- [ ] Add documentation.
- [ ] Find and fix any issues for On-Prem users

**Comment by marleypowell** [comment]
UI additions that will be completed in #7897

### Pull Request Dashboard Page
![image](https://user-images.githubusercontent.com/55280588/140750425-4255ef4c-cfdf-4724-bb80-d4182ab63d53.png)

### Pull Request Card - Simplified

![image](https://user-images.githubusercontent.com/55280588/140750634-5c0cca4d-9337-430c-8366-4343033878a3.png)


### Pull Request Card - Full
![image](https://user-images.githubusercontent.com/55280588/140750673-36a79a90-cd6b-4455-9e78-4d89a6ac1283.png)

**Comment by awanlin** [comment]
@marleypowell will you be continuing on with this or should we close it and work on new features as time permit or there is requests for changes?

**Comment by marleypowell** [comment]
> @marleypowell will you be continuing on with this or should we close it and work on new features as time permit or there is requests for changes?

I do plan on continuing with this but haven't really had much time to at the moment.
